import { summary } from "@actions/core";
import type { UsageItem } from "./run";

interface SummaryArgs {
  items: UsageItem[];
  totalCredits: number;
  estimatedCostUsd: number;
  pricePerCredit: number;
  scope: string;
  year: number;
  month?: number;
}

const fmtNum = (n: number, digits = 2) =>
  n.toLocaleString("en-US", { maximumFractionDigits: digits });

const fmtUsd = (n: number) =>
  n.toLocaleString("en-US", { style: "currency", currency: "USD" });

const groupBy = (
  items: UsageItem[],
  keyFn: (i: UsageItem) => string | undefined,
): Record<string, { credits: number; cost: number; items: number }> => {
  const out: Record<string, { credits: number; cost: number; items: number }> = {};
  for (const i of items) {
    const k = keyFn(i);
    if (!k) continue;
    const bucket = (out[k] ??= { credits: 0, cost: 0, items: 0 });
    bucket.credits += i.quantity || 0;
    bucket.cost += i.netAmount || 0;
    bucket.items += 1;
  }
  return out;
};

const topN = (
  groups: Record<string, { credits: number; cost: number; items: number }>,
  n = 10,
) =>
  Object.entries(groups)
    .sort((a, b) => b[1].credits - a[1].credits)
    .slice(0, n);

const dailyTrendMermaid = (items: UsageItem[]): string => {
  const byDay = groupBy(items, (i) => (i.date || "").slice(0, 10));
  const days = Object.keys(byDay).sort();
  if (days.length === 0) return "";
  const labels = days.map((d) => `"${d}"`).join(", ");
  const values = days.map((d) => byDay[d].credits.toFixed(2)).join(", ");
  return [
    "```mermaid",
    "xychart-beta",
    `    title "Daily AI Credits"`,
    `    x-axis [${labels}]`,
    `    y-axis "AIU"`,
    `    bar [${values}]`,
    "```",
  ].join("\n");
};

const tableRows = (
  rows: [string, { credits: number; cost: number; items: number }][],
): string[][] =>
  rows.map(([key, v]) => [
    key,
    fmtNum(v.credits),
    fmtUsd(v.cost),
    fmtNum(v.items, 0),
  ]);

export const writeJobSummary = async (args: SummaryArgs): Promise<void> => {
  const { items, totalCredits, estimatedCostUsd, pricePerCredit, scope, year, month } = args;

  const period = month ? `${year}-${String(month).padStart(2, "0")}` : `${year}`;

  const byModel = groupBy(items, (i) => i.sku || "(unknown sku)");
  const byUser = groupBy(items, (i) => i.username);
  const byRepo = groupBy(items, (i) => i.repositoryName);
  const byOrg = groupBy(items, (i) => i.organizationName);

  await summary
    .addHeading(`🧠 GitHub AI Credits Usage — ${scope}`, 1)
    .addRaw(`Period: **${period}** · Items: **${fmtNum(items.length, 0)}**`)
    .addBreak()
    .addTable([
      [
        { data: "Metric", header: true },
        { data: "Value", header: true },
      ],
      ["Total AI Credits (AIU)", fmtNum(totalCredits)],
      [`Estimated cost @ ${fmtUsd(pricePerCredit)}/credit`, fmtUsd(estimatedCostUsd)],
      ["Actual net amount (billed)", fmtUsd(items.reduce((s, i) => s + (i.netAmount || 0), 0))],
    ])
    .addHeading("Daily trend", 2)
    .addRaw(dailyTrendMermaid(items))
    .addHeading("Top SKUs / models", 2)
    .addTable([
      [
        { data: "SKU", header: true },
        { data: "Credits", header: true },
        { data: "Cost", header: true },
        { data: "Items", header: true },
      ],
      ...tableRows(topN(byModel)),
    ])
    .addHeading("Top users", 2)
    .addTable([
      [
        { data: "User", header: true },
        { data: "Credits", header: true },
        { data: "Cost", header: true },
        { data: "Items", header: true },
      ],
      ...tableRows(topN(byUser)),
    ])
    .addHeading("Top repositories", 2)
    .addTable([
      [
        { data: "Repo", header: true },
        { data: "Credits", header: true },
        { data: "Cost", header: true },
        { data: "Items", header: true },
      ],
      ...tableRows(topN(byRepo)),
    ])
    .addHeading("By organization", 2)
    .addTable([
      [
        { data: "Org", header: true },
        { data: "Credits", header: true },
        { data: "Cost", header: true },
        { data: "Items", header: true },
      ],
      ...tableRows(topN(byOrg, 20)),
    ])
    .addRaw(
      `\n_Generated by [\`austenstone/ai-credits-usage\`](https://github.com/austenstone/ai-credits-usage)._`,
    )
    .write();
};
